//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesApp.AppTier.Bridge.BizService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BizService.IBizService")]
    public interface IBizService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorById", ReplyAction="http://tempuri.org/IBizService/GetActorByIdResponse")]
        MoviesApp.Models.Actor GetActorById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorById", ReplyAction="http://tempuri.org/IBizService/GetActorByIdResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Actor> GetActorByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllActors", ReplyAction="http://tempuri.org/IBizService/GetAllActorsResponse")]
        System.Collections.Generic.List<MoviesApp.Models.Actor> GetAllActors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllActors", ReplyAction="http://tempuri.org/IBizService/GetAllActorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Actor>> GetAllActorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByName", ReplyAction="http://tempuri.org/IBizService/GetByNameResponse")]
        MoviesApp.Models.Actor GetByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByName", ReplyAction="http://tempuri.org/IBizService/GetByNameResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Actor> GetByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateActor", ReplyAction="http://tempuri.org/IBizService/CreateActorResponse")]
        MoviesApp.Models.Actor CreateActor(MoviesApp.Models.Actor actor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateActor", ReplyAction="http://tempuri.org/IBizService/CreateActorResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Actor> CreateActorAsync(MoviesApp.Models.Actor actor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorsByString", ReplyAction="http://tempuri.org/IBizService/GetActorsByStringResponse")]
        System.Collections.Generic.List<MoviesApp.Models.Actor> GetActorsByString(string actorstring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorsByString", ReplyAction="http://tempuri.org/IBizService/GetActorsByStringResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Actor>> GetActorsByStringAsync(string actorstring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetMovieById", ReplyAction="http://tempuri.org/IBizService/GetMovieByIdResponse")]
        MoviesApp.Models.Movie GetMovieById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetMovieById", ReplyAction="http://tempuri.org/IBizService/GetMovieByIdResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Movie> GetMovieByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllMovies", ReplyAction="http://tempuri.org/IBizService/GetAllMoviesResponse")]
        System.Collections.Generic.List<MoviesApp.Models.Movie> GetAllMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllMovies", ReplyAction="http://tempuri.org/IBizService/GetAllMoviesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Movie>> GetAllMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByTitle", ReplyAction="http://tempuri.org/IBizService/GetByTitleResponse")]
        MoviesApp.Models.Movie GetByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByTitle", ReplyAction="http://tempuri.org/IBizService/GetByTitleResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Movie> GetByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateMovie", ReplyAction="http://tempuri.org/IBizService/CreateMovieResponse")]
        MoviesApp.Models.Movie CreateMovie(MoviesApp.Models.OmdbMovie omdbmovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateMovie", ReplyAction="http://tempuri.org/IBizService/CreateMovieResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.Movie> CreateMovieAsync(MoviesApp.Models.OmdbMovie omdbmovie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorTagById", ReplyAction="http://tempuri.org/IBizService/GetActorTagByIdResponse")]
        MoviesApp.Models.ActorTag GetActorTagById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetActorTagById", ReplyAction="http://tempuri.org/IBizService/GetActorTagByIdResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> GetActorTagByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllActorTags", ReplyAction="http://tempuri.org/IBizService/GetAllActorTagsResponse")]
        System.Collections.Generic.List<MoviesApp.Models.ActorTag> GetAllActorTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllActorTags", ReplyAction="http://tempuri.org/IBizService/GetAllActorTagsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.ActorTag>> GetAllActorTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateActorTag", ReplyAction="http://tempuri.org/IBizService/CreateActorTagResponse")]
        MoviesApp.Models.ActorTag CreateActorTag(MoviesApp.Models.ActorTag actortag, int actorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateActorTag", ReplyAction="http://tempuri.org/IBizService/CreateActorTagResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> CreateActorTagAsync(MoviesApp.Models.ActorTag actortag, int actorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/UpdateActorTag", ReplyAction="http://tempuri.org/IBizService/UpdateActorTagResponse")]
        MoviesApp.Models.ActorTag UpdateActorTag(MoviesApp.Models.ActorTag actortag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/UpdateActorTag", ReplyAction="http://tempuri.org/IBizService/UpdateActorTagResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> UpdateActorTagAsync(MoviesApp.Models.ActorTag actortag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/DeleteActorTagRelationship", ReplyAction="http://tempuri.org/IBizService/DeleteActorTagRelationshipResponse")]
        void DeleteActorTagRelationship(MoviesApp.Models.ActorTag actortag, int actorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/DeleteActorTagRelationship", ReplyAction="http://tempuri.org/IBizService/DeleteActorTagRelationshipResponse")]
        System.Threading.Tasks.Task DeleteActorTagRelationshipAsync(MoviesApp.Models.ActorTag actortag, int actorid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetMovieTagById", ReplyAction="http://tempuri.org/IBizService/GetMovieTagByIdResponse")]
        MoviesApp.Models.MovieTag GetMovieTagById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetMovieTagById", ReplyAction="http://tempuri.org/IBizService/GetMovieTagByIdResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> GetMovieTagByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByMovie", ReplyAction="http://tempuri.org/IBizService/GetByMovieResponse")]
        System.Collections.Generic.List<MoviesApp.Models.MovieTag> GetByMovie(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetByMovie", ReplyAction="http://tempuri.org/IBizService/GetByMovieResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.MovieTag>> GetByMovieAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllMovieTags", ReplyAction="http://tempuri.org/IBizService/GetAllMovieTagsResponse")]
        System.Collections.Generic.List<MoviesApp.Models.MovieTag> GetAllMovieTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/GetAllMovieTags", ReplyAction="http://tempuri.org/IBizService/GetAllMovieTagsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.MovieTag>> GetAllMovieTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateMovieTag", ReplyAction="http://tempuri.org/IBizService/CreateMovieTagResponse")]
        MoviesApp.Models.MovieTag CreateMovieTag(MoviesApp.Models.MovieTag movietag, string movieid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/CreateMovieTag", ReplyAction="http://tempuri.org/IBizService/CreateMovieTagResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> CreateMovieTagAsync(MoviesApp.Models.MovieTag movietag, string movieid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/UpdateMovieTag", ReplyAction="http://tempuri.org/IBizService/UpdateMovieTagResponse")]
        MoviesApp.Models.MovieTag UpdateMovieTag(MoviesApp.Models.MovieTag movietag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/UpdateMovieTag", ReplyAction="http://tempuri.org/IBizService/UpdateMovieTagResponse")]
        System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> UpdateMovieTagAsync(MoviesApp.Models.MovieTag movietag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/DeleteMovieTagRelationship", ReplyAction="http://tempuri.org/IBizService/DeleteMovieTagRelationshipResponse")]
        void DeleteMovieTagRelationship(MoviesApp.Models.MovieTag movietag, string movieid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBizService/DeleteMovieTagRelationship", ReplyAction="http://tempuri.org/IBizService/DeleteMovieTagRelationshipResponse")]
        System.Threading.Tasks.Task DeleteMovieTagRelationshipAsync(MoviesApp.Models.MovieTag movietag, string movieid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBizServiceChannel : MoviesApp.AppTier.Bridge.BizService.IBizService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizServiceClient : System.ServiceModel.ClientBase<MoviesApp.AppTier.Bridge.BizService.IBizService>, MoviesApp.AppTier.Bridge.BizService.IBizService {
        
        public BizServiceClient() {
        }
        
        public BizServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MoviesApp.Models.Actor GetActorById(int id) {
            return base.Channel.GetActorById(id);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Actor> GetActorByIdAsync(int id) {
            return base.Channel.GetActorByIdAsync(id);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.Actor> GetAllActors() {
            return base.Channel.GetAllActors();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Actor>> GetAllActorsAsync() {
            return base.Channel.GetAllActorsAsync();
        }
        
        public MoviesApp.Models.Actor GetByName(string name) {
            return base.Channel.GetByName(name);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Actor> GetByNameAsync(string name) {
            return base.Channel.GetByNameAsync(name);
        }
        
        public MoviesApp.Models.Actor CreateActor(MoviesApp.Models.Actor actor) {
            return base.Channel.CreateActor(actor);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Actor> CreateActorAsync(MoviesApp.Models.Actor actor) {
            return base.Channel.CreateActorAsync(actor);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.Actor> GetActorsByString(string actorstring) {
            return base.Channel.GetActorsByString(actorstring);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Actor>> GetActorsByStringAsync(string actorstring) {
            return base.Channel.GetActorsByStringAsync(actorstring);
        }
        
        public MoviesApp.Models.Movie GetMovieById(string id) {
            return base.Channel.GetMovieById(id);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Movie> GetMovieByIdAsync(string id) {
            return base.Channel.GetMovieByIdAsync(id);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.Movie> GetAllMovies() {
            return base.Channel.GetAllMovies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.Movie>> GetAllMoviesAsync() {
            return base.Channel.GetAllMoviesAsync();
        }
        
        public MoviesApp.Models.Movie GetByTitle(string title) {
            return base.Channel.GetByTitle(title);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Movie> GetByTitleAsync(string title) {
            return base.Channel.GetByTitleAsync(title);
        }
        
        public MoviesApp.Models.Movie CreateMovie(MoviesApp.Models.OmdbMovie omdbmovie) {
            return base.Channel.CreateMovie(omdbmovie);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.Movie> CreateMovieAsync(MoviesApp.Models.OmdbMovie omdbmovie) {
            return base.Channel.CreateMovieAsync(omdbmovie);
        }
        
        public MoviesApp.Models.ActorTag GetActorTagById(int id) {
            return base.Channel.GetActorTagById(id);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> GetActorTagByIdAsync(int id) {
            return base.Channel.GetActorTagByIdAsync(id);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.ActorTag> GetAllActorTags() {
            return base.Channel.GetAllActorTags();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.ActorTag>> GetAllActorTagsAsync() {
            return base.Channel.GetAllActorTagsAsync();
        }
        
        public MoviesApp.Models.ActorTag CreateActorTag(MoviesApp.Models.ActorTag actortag, int actorid) {
            return base.Channel.CreateActorTag(actortag, actorid);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> CreateActorTagAsync(MoviesApp.Models.ActorTag actortag, int actorid) {
            return base.Channel.CreateActorTagAsync(actortag, actorid);
        }
        
        public MoviesApp.Models.ActorTag UpdateActorTag(MoviesApp.Models.ActorTag actortag) {
            return base.Channel.UpdateActorTag(actortag);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.ActorTag> UpdateActorTagAsync(MoviesApp.Models.ActorTag actortag) {
            return base.Channel.UpdateActorTagAsync(actortag);
        }
        
        public void DeleteActorTagRelationship(MoviesApp.Models.ActorTag actortag, int actorid) {
            base.Channel.DeleteActorTagRelationship(actortag, actorid);
        }
        
        public System.Threading.Tasks.Task DeleteActorTagRelationshipAsync(MoviesApp.Models.ActorTag actortag, int actorid) {
            return base.Channel.DeleteActorTagRelationshipAsync(actortag, actorid);
        }
        
        public MoviesApp.Models.MovieTag GetMovieTagById(int id) {
            return base.Channel.GetMovieTagById(id);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> GetMovieTagByIdAsync(int id) {
            return base.Channel.GetMovieTagByIdAsync(id);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.MovieTag> GetByMovie(string id) {
            return base.Channel.GetByMovie(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.MovieTag>> GetByMovieAsync(string id) {
            return base.Channel.GetByMovieAsync(id);
        }
        
        public System.Collections.Generic.List<MoviesApp.Models.MovieTag> GetAllMovieTags() {
            return base.Channel.GetAllMovieTags();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MoviesApp.Models.MovieTag>> GetAllMovieTagsAsync() {
            return base.Channel.GetAllMovieTagsAsync();
        }
        
        public MoviesApp.Models.MovieTag CreateMovieTag(MoviesApp.Models.MovieTag movietag, string movieid) {
            return base.Channel.CreateMovieTag(movietag, movieid);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> CreateMovieTagAsync(MoviesApp.Models.MovieTag movietag, string movieid) {
            return base.Channel.CreateMovieTagAsync(movietag, movieid);
        }
        
        public MoviesApp.Models.MovieTag UpdateMovieTag(MoviesApp.Models.MovieTag movietag) {
            return base.Channel.UpdateMovieTag(movietag);
        }
        
        public System.Threading.Tasks.Task<MoviesApp.Models.MovieTag> UpdateMovieTagAsync(MoviesApp.Models.MovieTag movietag) {
            return base.Channel.UpdateMovieTagAsync(movietag);
        }
        
        public void DeleteMovieTagRelationship(MoviesApp.Models.MovieTag movietag, string movieid) {
            base.Channel.DeleteMovieTagRelationship(movietag, movieid);
        }
        
        public System.Threading.Tasks.Task DeleteMovieTagRelationshipAsync(MoviesApp.Models.MovieTag movietag, string movieid) {
            return base.Channel.DeleteMovieTagRelationshipAsync(movietag, movieid);
        }
    }
}
