/*
Deployment script for C:\USERS\PERKINSD\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\MOVIESAPP\MOVIESAPP\APP_DATA\MOVIESDB.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\PERKINSD\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\MOVIESAPP\MOVIESAPP\APP_DATA\MOVIESDB.MDF"
:setvar DefaultFilePrefix "C_\USERS\PERKINSD\DOCUMENTS\VISUAL STUDIO 2015\PROJECTS\MOVIESAPP\MOVIESAPP\APP_DATA\MOVIESDB.MDF_"
:setvar DefaultDataPath "C:\Users\PerkinsD\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\PerkinsD\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                AUTO_SHRINK OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367)) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key ec70f665-7671-4739-bbf6-ffb9e8b8efea is skipped, element [dbo].[ActorMovieRelationships].[ActorID] (SqlSimpleColumn) will not be renamed to ActorMovieRelationshipID';


GO
PRINT N'Rename refactoring operation with key 608c158a-95fa-429e-b140-6300d852fcff is skipped, element [dbo].[Actors].[MovieID] (SqlSimpleColumn) will not be renamed to ActorID';


GO
PRINT N'Rename refactoring operation with key c098f4c7-7e76-4444-96aa-89975c354dee, 0fa66b28-ce41-460a-a798-b455cac73509 is skipped, element [dbo].[Actors].[Title] (SqlSimpleColumn) will not be renamed to Age';


GO
PRINT N'Rename refactoring operation with key 3107593e-d091-403e-b68e-1281dcde83e1, 0fa66b28-ce41-460a-a798-b455cac73509 is skipped, element [dbo].[Actors].[Year] (SqlSimpleColumn) will not be renamed to Age';


GO
PRINT N'Rename refactoring operation with key 5be121bc-2eaf-4795-a49c-886599f52106, 6fc9ca9c-a55c-4443-a416-9e965baaa49c is skipped, element [dbo].[MovieTags].[ActorID] (SqlSimpleColumn) will not be renamed to MovieTagID';


GO
PRINT N'Rename refactoring operation with key 2a4d7f6b-b483-445b-8709-48d92747e1d7 is skipped, element [dbo].[MovieTags].[Name] (SqlSimpleColumn) will not be renamed to TagDescription';


GO
PRINT N'Rename refactoring operation with key 4f687991-3104-4db0-8b3f-8bbc4e26e5e8 is skipped, element [dbo].[MovieTags].[Age] (SqlSimpleColumn) will not be renamed to MovieID';


GO
PRINT N'Rename refactoring operation with key e4cb7377-4aae-4ad1-b94f-4f204320d64c is skipped, element [dbo].[ActorMovieRelationships].[Name] (SqlSimpleColumn) will not be renamed to MovieID';


GO
PRINT N'Rename refactoring operation with key 1dfa49f8-f7ca-483c-bf68-2447b81fb96e is skipped, element [dbo].[ActorMovieRelationships].[Age] (SqlSimpleColumn) will not be renamed to ActorID';


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '608c158a-95fa-429e-b140-6300d852fcff')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('608c158a-95fa-429e-b140-6300d852fcff')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'c098f4c7-7e76-4444-96aa-89975c354dee')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('c098f4c7-7e76-4444-96aa-89975c354dee')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3107593e-d091-403e-b68e-1281dcde83e1')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3107593e-d091-403e-b68e-1281dcde83e1')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0fa66b28-ce41-460a-a798-b455cac73509')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0fa66b28-ce41-460a-a798-b455cac73509')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '5be121bc-2eaf-4795-a49c-886599f52106')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('5be121bc-2eaf-4795-a49c-886599f52106')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '2a4d7f6b-b483-445b-8709-48d92747e1d7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('2a4d7f6b-b483-445b-8709-48d92747e1d7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '4f687991-3104-4db0-8b3f-8bbc4e26e5e8')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('4f687991-3104-4db0-8b3f-8bbc4e26e5e8')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6fc9ca9c-a55c-4443-a416-9e965baaa49c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6fc9ca9c-a55c-4443-a416-9e965baaa49c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ec70f665-7671-4739-bbf6-ffb9e8b8efea')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ec70f665-7671-4739-bbf6-ffb9e8b8efea')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'e4cb7377-4aae-4ad1-b94f-4f204320d64c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('e4cb7377-4aae-4ad1-b94f-4f204320d64c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '1dfa49f8-f7ca-483c-bf68-2447b81fb96e')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('1dfa49f8-f7ca-483c-bf68-2447b81fb96e')

GO

GO
PRINT N'Update complete.';


GO
